vidispine:
  user: "admin"
  env: "PROD"
mediaconvert:
  url: https://p642t1g0ai.execute-api.us-west-2.amazonaws.com/prod
logging:
  file:
    name: application-debug.log
  level:
    root: ERROR
    fox.mc.backfill.mediaconvert: INFO